### ISSUE TITLE
Add a generator for creating the User model

### ISSUE THREAD

**Issue by excid3** [excid3/revise_auth#1]
The generator should create:

- [ ] A migration with the required columns. See: https://github.com/excid3/revise_auth/blob/main/test/dummy/db/migrate/20230112011459_create_users.rb
- [ ] A User model with `include ReviseAuth::Model`

`rails revise_auth:install`

**Comment by gathuku** [comment]
Do you need a hand on this?

**Comment by excid3** [comment]
@gathuku Sure!

**Comment by excid3** [comment]
I have added a views generator that you can use as an example. The user one will probably need it's own folder with a `templates` folder for the migration and model though.

**Comment by gathuku** [comment]
Cool looking at it.
