### ISSUE TITLE
Support `authenticate: password_challenge`

### ISSUE THREAD

**Issue by kylekeesling** [excid3/revise_auth#21]
A little while back I created a [PR for for authentication-zero](https://github.com/rails/rails/pull/43688) to support the [upcoming feature in Rails 7.1](https://github.com/rails/rails/pull/43688) that allows you to provide a `password_challenge` param directly to the `authenticate` method call.

I'd be happy to submit a PR if you're interested in supporting it in this project.

**Comment by excid3** [comment]
I was planning to backport that for < 7.0, so that would be awesome. 👍
