### ISSUE TITLE
use `generates_token_for`

### ISSUE THREAD

**Issue by kylekeesling** [excid3/revise_auth#23]
Would also be happy to take a crack at swapping in [`generates_token_for`](https://github.com/rails/rails/pull/44189) for the `confirmation_token` if interested.

**Comment by excid3** [comment]
I didn't even realize this was added. Sweet!

Heck. Revise Auth might just need to target Rails 7.1 lol.

**Comment by kylekeesling** [comment]
I know! It would make it much easier in many ways. It could be a nice compliment to some of the established libraries, and a great option for new folks coming into Rails. 

I guess you'd just have to weigh how many folks you imagine would be migrating to this library versus using it in a greenfield app.

**Comment by kylekeesling** [comment]
At any rate if your cool with it I can submit a PR 😁

**Comment by excid3** [comment]
Please do! 

I'm mostly intending this for new apps but I do want to support rails 7+. But also if this turns out well, I might switch my apps to it from Devise eventually.
