### ISSUE TITLE
`rails g revise_auth:model` parameters behaving unexpectedly

### ISSUE THREAD

**Issue by redbassett** [excid3/revise_auth#63]
I am just trying out revise for the first time and following the documentation in the README:

> Optionally, you can add other fields such as first_name and last_name:
> 
> $ rails g revise_auth:model first_name last_name

I tried running the command `rails g revise_auth:model name` expecting a model called `User` with a field called `Name`, but instead I got a revise model `Name`:

>     generate  model
>        rails  generate model name email:string:index password_digest:string confirmation_token:string confirmed_at:datetime confirmation_sent_at:datetime unconfirmed_email:string
>       invoke  active_record
>       create    db/migrate/20240225175836_create_names.rb
>       create    app/models/name.rb
>       invoke    test_unit
>       create      test/models/name_test.rb
>       create      test/fixtures/names.yml
>       insert  app/models/name.rb
>       insert  db/migrate/20240225175836_create_names.rb

It makes sense to be able to rename the model, however based on the quoted part of the documentation this is inaccurate. Is this an unexpected behavior or outdated docs?

**Comment by excid3** [comment]
Works fine on v0.5 for me. Please provide your gem version and any other details.

**Comment by redbassett** [comment]
I believe I was running v0.5 when the issue occurred, but I am not certain. I will let you know if the issue is still occurring for me when I get a chance to test it, but thank you for confirming that it works as expected for you currently, it was likely something wrong on my end.
