### ISSUE TITLE
RegistrationsController#create should behave the same as SessionsController#create

### ISSUE THREAD

**Issue by Youdaman** [excid3/revise_auth#81]
In the SessionsController it has:
```ruby
      redirect_to resolve_after_login_path
```
Which allows me to have logic like:
```ruby
    if user_signed_in?
      current_user.set_payment_processor :stripe, stripe_account: stripe_account
      @checkout_session = current_user.payment_processor.checkout(mode: "payment", line_items: @game.price_id)
    else
      session[:user_return_to] = @rsvp_link
    end
```
So that when a user hits an event registration page, if they're logged in it shows them the checkout button, otherwise it prompts them to either login or sign up.

If they have an account and login, they're redirected back to the event page and can continue with the checkout, however if they don't have an account and choose to sign up, they get redirected to the root page due to the following in RegistrationsController:
```ruby
      redirect_to root_path
```

It would be nice if the RegistrationsController also used/had `resolve_after_login_path` so that the `:user_return_to` session variable was honoured for new users.

I had tried to use `after_login_path` as per the docs to do something like:
```ruby
class ApplicationController < ActionController::Base
  def after_login_path
    if session[:user_return_to].present?
      session[:user_return_to]
    else
      root_path
    end
  end
end
```

But that ran into the same issue because it's only the `resolve_after_login_path` method in the SessionsController that actually tries to use `after_login_path`:

```ruby
  def resolve_after_login_path
    try(:after_login_path) || return_to_location || root_path
  end
```

I would create a PR but a) I'm a Rails noob and b) you'd likely want to refactor it into a helper or put it somewhere outside the controllers if more than one uses the same method, and I'm not sure where that would best be :)

**Comment by excid3** [comment]
Yep, seems reasonable to me.
