### ISSUE TITLE
Errors do not display for login/sign_up custom views unless turbo is disable on the forms

### ISSUE THREAD

**Issue by Youdaman** [excid3/revise_auth#87]
When I tried signing up using an existing email it would just reload the sign_up form, and after some searching I found this answer on SO that suggested disabling turbo on the forms with `data: { turbo: false }` https://stackoverflow.com/a/71756926

After doing this for both the new/edit templates (which I'd generated with `rails g revise_auth:views` as per the readme) the forms correctly displayed errors like "Email has already been taken" etc.

**Comment by excid3** [comment]
Controllers all respond with the proper unprocessable entity status which is what Turbo requires for errors.
Also confirmed it works fine in the test/dummy app with Turbo.

<img width="1522" alt="Screenshot 2024-07-02 at 8 39 44 AM" src="https://github.com/excid3/revise_auth/assets/67093/2089c695-1ab9-4037-a1fd-a2914f1a4bc0">

**Comment by Youdaman** [comment]
Sorry, my bad.

I'd added a reload for turbo to counteract differences between pages driven by my controllers and those handled by the High Voltage static page engine... I've updated them accordingly to use the turbo-root directive instead and that seems to work:

application layout:
```
    <!--<meta name="turbo-visit-control" content="reload">-->
    <meta name="turbo-root" content="/app">
```

static pages layout:
```
    <!--<meta name="turbo-visit-control" content="reload">-->
    <meta name="turbo-root" content="/static">
```

I don't think the `content` value really matters right? As long as it's different then turbo knows that it should reload only then, and in my case the ReviseAuth controllers and my other controllers all use the application layout with `/app` as its value while I've set the pages managed by High Voltage to use another one (currently called `home.html.erb` even though I should probably rename to `static.html.erb`) with `/static` as the value.

The reload was messing with the display of the error messages by reloading the form sans messages!

Sorry for the false alarm! 😅

**Comment by Youdaman** [comment]
For anyone reading this in the future, turns out my "fix" using the turbo-root wasn't right either because it prevented the logout link using the confirm and method data attributes, e.g. `data: { turbo_confirm: "Are you sure?", turbo_method: :delete }` stopped working and the user didn't see a confirmation dialog and the link used the GET method instead.

The thing I was trying to overcome was some stylesheets being loaded in one layout that I didn't want loaded in another, hence trying the turbo-root thing -- turns out the real solution was to add `data-turbo-track="dynamic"` to the stylesheet links, e.g.
```
    <link rel="stylesheet" href="main.css" data-turbo-track="dynamic"/>
```
> When a page depends on external assets like CSS stylesheets that other pages do not, it can be useful to remove them when navigating away from the page.
-- https://turbo.hotwired.dev/handbook/drive#removing-assets-when-they-change

**Comment by iamajvillalobos** [comment]
Thanks! I encountered this too when I was using a different layout for my auth page. I needed to add this `data-turbo-track` thing in my other layouts because the auth one persist. But also weird since I am using tailwindcss so basically they are using the same stylesheet.
